### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by acroo111** [finlay-x/gulp-extract-critical-css#1]
Hello - I'm working breaking out critical styles in gulp scss workflow and gave this a spin. 

I receive  "MODULE_NOT_FOUND" when attempting to gulp init. In my gulp file I do not need the "./" for other modules but have tried it both ways with failure.

const extractCriticalCss = require('./extract-critical-css');
const extractCriticalCss = require('extract-critical-css');

My gulp.js

`const { src, dest, watch, series, parallel } = require('gulp');
const browserSync = require('browser-sync').create();
const sass = require('gulp-sass')(require('sass'));
const sourcemaps = require('gulp-sourcemaps');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const postcss = require('gulp-postcss');
const autoprefixer = require('autoprefixer');
const replace = require('gulp-replace');
const cssnano = require('cssnano');
const cssVersion = new Date().getTime();
const sassRoot = 'assets/scss/*.scss';
const sassThemeFiles = 'assets/scss/**/*.scss';
const sassBlockFiles = 'core/blocks/**/*.scss';
const jsLibraryFiles = 'assets/js/libs/*.js';
const jsBlockFiles = 'core/blocks/**/*.js';
const jsFiles = 'assets/js/development/*.js';
const jsWpAdmin = 'assets/js/admin/*.js';
const rollup = require('gulp-better-rollup');
const rename = require('gulp-rename');
const sassGlob = require('gulp-sass-glob');
const babel = require('rollup-plugin-babel');
const resolve = require('rollup-plugin-node-resolve');
const commonjs = require('rollup-plugin-commonjs');
const extractCriticalCss = require('./extract-critical-css');

// function criticalCSS() {
//     return gulp.src('dist/css/theme.css')
//       .pipe(extractCriticalCss())
//       .pipe(gulp.dest('dist/css/'));
// }
// exports.criticalCSS = series(criticalCSS)

function scssThemeTask() {
    return src(sassRoot)
        .pipe(sourcemaps.init())
        .pipe(sassGlob())
        .pipe(sass())
        .pipe(postcss([autoprefixer('last 2 version'), cssnano()]))
        .pipe(criticalCss())
        .pipe(dest('dist/css'))
        // .pipe(extractCriticalCss())
        .pipe(dest('dist/css'))
        .pipe(sourcemaps.write('.'));
}

function blockScssTask() {
    return src(sassBlockFiles)
        .pipe(sassGlob())
        .pipe(sass())
        .pipe(postcss([autoprefixer('last 2 version'), cssnano()]))
        // .pipe(criticalCss())
        .pipe(dest(sassBlockFiles));
}

function jsAdminTask() {
    return src([jsWpAdmin])
        .pipe(
            rollup({ plugins: [
                    babel(),
                    resolve({
                        allowRealFiles: true
                    }),
                    commonjs()
                ]
            }, 'umd'))
        .pipe(uglify())
        .pipe(dest('dist/js'));
}

function jsTask() {
    return src([jsLibraryFiles,jsFiles,jsBlockFiles])
        .pipe(
            rollup({ plugins: [
                    babel(),
                    resolve({
                        allowRealFiles: true
                    }),
                    commonjs()
                ]
            }, 'umd'))
        .pipe(concat('scripts.js'))
        .pipe(dest('dist/js'))
        .pipe(uglify())
        .pipe(rename({suffix: '.min'}))
        .pipe(dest('dist/js'));
}

function watchTask() {
    // Watch for changes in any SCSS or JS files, and run the scssThemeTask,
    // jsTask, and preventCachingTask functions whenever there is a change.
    watch(
        [sassRoot,sassThemeFiles,sassBlockFiles,jsFiles,jsLibraryFiles,jsBlockFiles,jsWpAdmin],
        series(
            parallel(scssThemeTask, jsTask,jsAdminTask),
        )
    );
}

// Export run 'gulp'
exports.default = series(
    parallel(scssThemeTask, jsTask, jsAdminTask),
    watchTask
);`

**Comment by finlay-x** [comment]
Apologies, thats a mistake in the README. 

The example require within the gulpfile.js should read:
`const extractCriticalCss = require('gulp-extract-critical-css')`

If you can try that and let me know if that fixes the issue

**Comment by acroo111** [comment]
It looks like that worked concerning spinning up - thank you!
